import React, { useEffect, useState } from 'react';
import AdminSidebar from '../components/AdminSidebar';

type Settings = { model: string; temperature: string; maxTokens: string; opening: string; closing: string; simulator: boolean };
const defaults: Settings = { model: 'qwen3:8b', temperature: '0.35', maxTokens: '300', opening: '08:00', closing: '18:00', simulator: true };

const SettingsPage: React.FC = () => {
  const [settings, setSettings] = useState<Settings>(defaults);
  const [saved, setSaved] = useState(false);

  useEffect(() => { const stored = localStorage.getItem('water-crm-settings'); if (stored) setSettings({ ...defaults, ...JSON.parse(stored) }); }, []);
  const update = (key: keyof Settings, value: string | boolean) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { localStorage.setItem('water-crm-settings', JSON.stringify(settings)); setSaved(true); setTimeout(() => setSaved(false), 2500); };

  return <div className="min-h-screen bg-slate-950 px-5 py-6 text-slate-100 md:px-8 ml-64"><AdminSidebar /><div className="mx-auto max-w-5xl"><p className="text-xs uppercase tracking-[0.2em] text-teal-400">Administración</p><h1 className="mt-2 text-3xl font-semibold">Configuración</h1><p className="mt-1 text-sm text-slate-500">Parámetros operativos del simulador y de Ollama.</p>{saved && <div className="mt-5 border border-emerald-700 bg-emerald-950/50 px-4 py-3 text-sm text-emerald-300">Configuración guardada en este navegador.</div>}<div className="mt-6 grid gap-6 md:grid-cols-2"><section className="border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Inteligencia artificial</h2><label className="mt-5 block text-xs text-slate-500">Modelo Ollama<select value={settings.model} onChange={(e) => update('model', e.target.value)} className="mt-2 w-full border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200"><option>qwen3:8b</option><option>llama3.2</option><option>mistral</option></select></label><label className="mt-4 block text-xs text-slate-500">Temperatura<input type="number" min="0" max="1" step="0.05" value={settings.temperature} onChange={(e) => update('temperature', e.target.value)} className="mt-2 w-full border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200" /></label><label className="mt-4 block text-xs text-slate-500">Máximo de tokens<input type="number" value={settings.maxTokens} onChange={(e) => update('maxTokens', e.target.value)} className="mt-2 w-full border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200" /></label></section><section className="border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Atención</h2><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-xs text-slate-500">Apertura<input type="time" value={settings.opening} onChange={(e) => update('opening', e.target.value)} className="mt-2 w-full border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200" /></label><label className="text-xs text-slate-500">Cierre<input type="time" value={settings.closing} onChange={(e) => update('closing', e.target.value)} className="mt-2 w-full border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200" /></label></div><label className="mt-6 flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={settings.simulator} onChange={(e) => update('simulator', e.target.checked)} /> Modo simulador activo</label><p className="mt-5 text-xs leading-5 text-slate-500">Los secretos de WhatsApp no se guardan en el navegador. Configúralos mediante el archivo de entorno del backend.</p></section></div><button onClick={save} className="mt-6 bg-teal-500 px-5 py-3 text-sm font-semibold text-slate-950 hover:bg-teal-400">Guardar cambios</button></div></div>;
};

export default SettingsPage;